"""Tests for width ratio preservation feature."""

import pytest
import pandas as pd

from spell_card_generator.utils.file_scanner import FileScanner
from spell_card_generator.generators.latex_generator import (
    LaTeXGenerator,
    PreservationOptions,
)


class TestWidthRatioExtraction:
    """Test width ratio extraction from existing cards."""

    def test_extract_custom_width_ratio(self, tmp_path):
        r"""Test extraction of custom width ratio from \spellcardinfo[0.55]{}."""
        card_file = tmp_path / "test_card.tex"
        card_content = """%%%
%%% file content generated by spell_card_generator.py
%%%
\\begin{spellcard}{sor}{Test Spell}{1}
  \\newcommand{\\name}{Test Spell}
  \\spellcardinfo[0.55]{}
  \\spellcardqr{\\urlenglish}
  % SPELL DESCRIPTION BEGIN
  Test description
  % SPELL DESCRIPTION END
\\end{spellcard}
"""
        card_file.write_text(card_content, encoding="utf-8")

        analysis = FileScanner.analyze_existing_card(card_file)
        assert analysis["width_ratio"] == "0.55"

    def test_extract_default_width_ratio(self, tmp_path):
        r"""Test that default \spellcardinfo{} returns None for width_ratio."""
        card_file = tmp_path / "test_card.tex"
        card_content = """%%%
%%% file content generated by spell_card_generator.py
%%%
\\begin{spellcard}{sor}{Test Spell}{1}
  \\newcommand{\\name}{Test Spell}
  \\spellcardinfo{}
  \\spellcardqr{\\urlenglish}
  % SPELL DESCRIPTION BEGIN
  Test description
  % SPELL DESCRIPTION END
\\end{spellcard}
"""
        card_file.write_text(card_content, encoding="utf-8")

        analysis = FileScanner.analyze_existing_card(card_file)
        assert analysis["width_ratio"] is None

    def test_extract_various_ratios(self, tmp_path):
        """Test extraction of various valid ratio values."""
        test_cases = ["0.50", "0.55", "0.60", "0.65", "0.70", "0.75"]

        for ratio in test_cases:
            card_file = tmp_path / f"test_card_{ratio}.tex"
            card_content = f"""\\spellcardinfo[{ratio}]{{}}"""
            card_file.write_text(card_content, encoding="utf-8")

            analysis = FileScanner.analyze_existing_card(card_file)
            assert analysis["width_ratio"] == ratio, f"Failed for ratio {ratio}"

    def test_invalid_ratio_ignored(self, tmp_path):
        """Test that invalid ratio values are ignored."""
        test_cases = [
            "1.5",  # Greater than 1
            "-0.5",  # Negative
            "0",  # Zero
            "invalid",  # Not a number
        ]

        for ratio in test_cases:
            card_file = tmp_path / f"test_card_{ratio}.tex"
            card_content = f"""\\spellcardinfo[{ratio}]{{}}"""
            card_file.write_text(card_content, encoding="utf-8")

            analysis = FileScanner.analyze_existing_card(card_file)
            assert (
                analysis["width_ratio"] is None
            ), f"Invalid ratio {ratio} should be ignored"

    def test_nonexistent_file(self, tmp_path):
        """Test analyze_existing_card with nonexistent file."""
        nonexistent = tmp_path / "nonexistent.tex"
        analysis = FileScanner.analyze_existing_card(nonexistent)
        assert analysis == {}


class TestWidthRatioGeneration:
    """Test width ratio preservation in LaTeX generation."""

    @pytest.fixture
    def spell_data(self):
        """Create sample spell data."""
        return pd.Series(
            {
                "name": "Test Spell",
                "school": "evocation",
                "sor": "1",
                "description": "Test description",
                "description_formatted": "Test description",
                "components": "V, S",
                "range": "medium",
                "saving_throw": "none",
                "spell_resistance": "yes",
            }
        )

    def test_generate_with_custom_width_ratio(self, spell_data):
        """Test generation with preserved custom width ratio."""
        generator = LaTeXGenerator()
        result, conflicts = generator.generate_spell_latex(
            spell_data, "sor", preserved_width_ratio="0.55"
        )

        assert len(conflicts) == 0
        assert "\\spellcardinfo[0.55]{}" in result
        assert "\\spellcardinfo{}" not in result

    def test_generate_with_default_width_ratio(self, spell_data):
        """Test generation without custom width ratio (default)."""
        generator = LaTeXGenerator()
        result, conflicts = generator.generate_spell_latex(spell_data, "sor")

        assert len(conflicts) == 0
        assert "\\spellcardinfo{}" in result
        assert "\\spellcardinfo[" not in result

    def test_generate_with_none_width_ratio(self, spell_data):
        """Test generation with explicit None width ratio."""
        generator = LaTeXGenerator()
        result, conflicts = generator.generate_spell_latex(
            spell_data, "sor", preserved_width_ratio=None
        )

        assert len(conflicts) == 0
        assert "\\spellcardinfo{}" in result
        assert "\\spellcardinfo[" not in result


class TestWidthRatioPreservationIntegration:
    """Integration tests for width ratio preservation during regeneration."""

    @pytest.fixture
    def temp_spell_dir(self, tmp_path):
        """Create temporary spell directory structure."""
        spell_dir = tmp_path / "src" / "spells" / "sor" / "1"
        spell_dir.mkdir(parents=True)
        return spell_dir

    @pytest.fixture
    def spell_data(self):
        """Create sample spell data."""
        return pd.Series(
            {
                "name": "Test Spell",
                "school": "evocation",
                "sor": "1",
                "description": "Test description",
                "description_formatted": "Test description",
                "components": "V, S",
                "range": "medium",
                "saving_throw": "none",
                "spell_resistance": "yes",
                "source": "Core",
            }
        )

    def test_preserve_width_ratio_on_regeneration(
        self, temp_spell_dir, spell_data, monkeypatch
    ):
        """Test that width ratio is preserved when regenerating existing card."""
        # Create existing card with custom width ratio
        existing_card = temp_spell_dir / "Test Spell.tex"
        existing_content = """%%%
%%% file content generated by spell_card_generator.py
%%%
\\begin{spellcard}{sor}{Test Spell}{1}
  \\newcommand{\\name}{Test Spell}
  \\newcommand{\\school}{evocation}
  \\spellcardinfo[0.55]{}
  % SPELL DESCRIPTION BEGIN
  Original description
  % SPELL DESCRIPTION END
\\end{spellcard}
"""
        existing_card.write_text(existing_content, encoding="utf-8")

        # Mock the output base path to use our temp directory
        monkeypatch.setattr(
            "spell_card_generator.utils.paths.PathConfig.get_output_base_path",
            lambda: temp_spell_dir.parent.parent.parent,
        )

        # Generate card with overwrite=True
        generator = LaTeXGenerator()
        selected_spells = [("sor", "Test Spell", spell_data)]

        preservation_opts = PreservationOptions(
            preserve_description={"Test Spell": False},  # Don't preserve description
        )

        generated, skipped, conflicts = generator.generate_cards(
            selected_spells,
            overwrite=True,
            preservation_options=preservation_opts,
        )

        # Verify card was generated
        assert len(generated) == 1
        assert len(skipped) == 0
        assert len(conflicts) == 0

        # Read regenerated content
        regenerated_content = existing_card.read_text(encoding="utf-8")

        # Verify width ratio was preserved
        assert "\\spellcardinfo[0.55]{}" in regenerated_content
        assert "\\spellcardinfo{}" not in regenerated_content

    def test_fallback_to_default_when_no_custom_ratio(
        self, temp_spell_dir, spell_data, monkeypatch
    ):
        """Test that default ratio is used when existing card has no custom ratio."""
        # Create existing card without custom width ratio
        existing_card = temp_spell_dir / "Test Spell.tex"
        existing_content = """%%%
%%% file content generated by spell_card_generator.py
%%%
\\begin{spellcard}{sor}{Test Spell}{1}
  \\newcommand{\\name}{Test Spell}
  \\spellcardinfo{}
  % SPELL DESCRIPTION BEGIN
  Original description
  % SPELL DESCRIPTION END
\\end{spellcard}
"""
        existing_card.write_text(existing_content, encoding="utf-8")

        # Mock the output base path
        monkeypatch.setattr(
            "spell_card_generator.utils.paths.PathConfig.get_output_base_path",
            lambda: temp_spell_dir.parent.parent.parent,
        )

        # Generate card with overwrite=True
        generator = LaTeXGenerator()
        selected_spells = [("sor", "Test Spell", spell_data)]

        generated, skipped, conflicts = generator.generate_cards(
            selected_spells, overwrite=True
        )

        # Read regenerated content
        regenerated_content = existing_card.read_text(encoding="utf-8")

        # Verify default ratio is used
        assert "\\spellcardinfo{}" in regenerated_content
        assert "\\spellcardinfo[" not in regenerated_content
        assert len(conflicts) == 0
